#pragma once

//#########################
//Pekka Kana 2
//Copyright (c) 2003 Janne Kivilahti
//#########################

/**
 * @brief 
 * Sprite constants.
 */

#pragma once


namespace libgreta{
#define PK2SPRITE_CURRENT_VERSION "2.0"


//Spite file values

enum {

    ANIMATION_IDLE, //0
    ANIMATION_WALKING, //1
    ANIMATION_JUMP_UP, //2
    ANIMATION_JUMP_DOWN, //3
    ANIMATION_SQUAT, //4
    ANIMATION_DAMAGE, //5
    ANIMATION_DEATH, //6
    ANIMATION_ATTACK1, //7
    ANIMATION_ATTACK2, //8

    /**
     * @brief 
     * Reserved for future AIs, scripting, etc
     */
    ANIMATION_SPECIAL1, //9
    ANIMATION_SPECIAL2 //10
};

enum {

    SOUND_DAMAGE,
    SOUND_DESTRUCTION,
    SOUND_ATTACK1,
    SOUND_ATTACK2,
    SOUND_RANDOM,
    SOUND_SPECIAL1,
    SOUND_SPECIAL2

};

enum {

    EFFECT_NONE,
    EFFECT_STARS,
    EFFECT_SMOKE,
    EFFECT_THUNDER,

};

enum { //Damage

    DAMAGE_SELF_DESTRUCTION = -2,
    DAMAGE_WEAK_SELF_DESTRUCTION = -1,

    DAMAGE_NONE = 0, //0
    DAMAGE_IMPACT, //1
    DAMAGE_DROP, //2
    DAMAGE_NOISE, //3
    DAMAGE_FIRE, //4
    DAMAGE_WATER, // 5
    DAMAGE_SNOW, //6
    DAMAGE_BONUS, //7
    DAMAGE_ELECTRIC, //8
    DAMAGE_MAGIC, //9
    DAMAGE_COMPRESSION, //10
    DAMAGE_SMELL, //11
    DAMAGE_SUPERMODE, //12
    DAMAGE_STITCH //13
};

enum {

    TYPE_NOTHING, //0
    TYPE_GAME_CHARACTER, //1
    TYPE_BONUS, //2
    TYPE_PROJECTILE, //3
    TYPE_TELEPORT, //4
    TYPE_BACKGROUND, //5
    TYPE_FOREGROUND, //6

    TYPE_CHECKPOINT, //7 Reserved, not implemented
    TYPE_EXIT, //8 Reserved, not implemented

    TYPE_BLACK_HOLE, //9

};

enum {

    COLOR_GRAY      = 0,
    COLOR_BLUE      = 32,
    COLOR_RED       = 64,
    COLOR_GREEN     = 96,
    COLOR_ORANGE    = 128,
    COLOR_VIOLET    = 160,
    COLOR_TURQUOISE = 192,
    COLOR_NORMAL    = 255

};

enum { //Destruction Effect

    FX_DESTRUCT_NO_EFFECT, //0
    FX_DESTRUCT_FEATHERS, //1
    FX_DESTRUCT_STARS_GRAY, //2
    FX_DESTRUCT_STARS_BLUE, //3
    FX_DESTRUCT_STARS_RED, //4
    FX_DESTRUCT_STARS_GREEN, //5
    FX_DESTRUCT_STARS_ORANGE, //6
    FX_DESTRUCT_STARS_VIOLET, //7
    FX_DESTRUCT_STARS_TURQUOISE, //8
    FX_DESTRUCT_EXPLOSION_GRAY, //9
    FX_DESTRUCT_EXPLOSION_BLUE, //10
    FX_DESTRUCT_EXPLOSION_RED, //11
    FX_DESTRUCT_EXPLOSION_GREEN, //12
    FX_DESTRUCT_EXPLOSION_ORANGE, //13
    FX_DESTRUCT_EXPLOSION_VIOLET, //14
    FX_DESTRUCT_EXPLOSION_TURQUOISE, //15
    FX_DESTRUCT_SMOKE_GRAY, //16
    FX_DESTRUCT_SMOKE_BLUE, //17
    FX_DESTRUCT_SMOKE_RED, //18
    FX_DESTRUCT_SMOKE_GREEN, //19
    FX_DESTRUCT_SMOKE_ORANGE, //20
    FX_DESTRUCT_SMOKE_VIOLET, //21
    FX_DESTRUCT_SMOKE_TURQUOISE, //22
    FX_DESTRUCT_SMOKECLOUDS, //23

    /**
     * @brief 
     * New GE destruction effects 
     */
    FX_DESTRUCT_SPLASH_GRAY, //24
    FX_DESTRUCT_SPLASH_BLUE, //25
    FX_DESTRUCT_SPLASH_RED, //26,
    FX_DESTRUCT_SPLASH_GREEN, //27,
    FX_DESTRUCT_SPLASH_ORANGE, //28,
    FX_DESTRUCT_SPLASH_VIOLET, //29
    FX_DESTRUCT_SPLASH_TURQUOISE, //30

    FX_DESTRUCT_SMOKELESS_EXPLOSION_GRAY, //31
    FX_DESTRUCT_SMOKELESS_EXPLOSION_BLUE, //32
    FX_DESTRUCT_SMOKELESS_EXPLOSION_RED, //33
    FX_DESTRUCT_SMOKELESS_EXPLOSION_GREEN, //34
    FX_DESTRUCT_SMOKELESS_EXPLOSION_ORANGE, //35
    FX_DESTRUCT_SMOKELESS_EXPLOSION_VIOLET, //36
    FX_DESTRUCT_SMOKELESS_EXPLOSION_TURQUOISE, //37
    
    /**
     * @brief 
     * Animated
     */
    FX_DESTRUCT_ANIMATED = 100

};

enum {

    BONUSITEM_NOTHING,
    BONUSITEM_KEY,
    BONUSITEM_SCORE

};

}